#ifndef UPDATE_RUS_H
#define UPDATE_RUS_H
#include "problemDefines.h"
__device__ void update_RUs(float lambda,
                float dt,
                float kCa_plus,
                float kCa_minus,
                float randNum[N_RU],
                float rand_drug[N_RU],
                int   RU[N_RU],
                bool caRU[N_RU],
                float * kB_plus,
                float * kB_minus,
                float * k1_plus_drug,
                float * k1_plus_baseline,
                float * k1_minus,
                float k2_plus_drug,
                float k2_plus_baseline,
                float k2_minus,
                float k3_plus_drug,
                float k3_plus_baseline,
                float k3_minus,
                float *k4_plus_drug,
                float *k4_plus_baseline,
                float *k4_minus,
                float percent_drug,
                float k_force_drug,
                float k_force_baseline, 
                float k_plus_SR_drug,
                float k_plus_SR_baseline, 
                float k_minus_SR,
                float k_plus_SS, 
                float k_minus_SS,
                float f,
                float * ATPcounter
               );
#endif // UPDATE_RUS_H
